[project]
name            = "cordex"
version         = "0.1.0"
description     = "Development for the discord bot Cordex"
requires-python = ">=3.12"
dependencies    = [
    "discord.py",
    "basedpyright",
]

[tool.uv]
package = false

[tool.basedpyright]
typeCheckingMode = "all"
venvPath         = "."
venv             = ".venv"
pythonVersion    = "3.14"
include          = ["."]
exclude          = ["build"]

reportDeprecated                    = "error"
reportImplicitStringConcatenation   = false
reportUnannotatedClassAttribute     = "error"
reportIgnoreCommentWithoutRule      = "error"
reportMissingParameterType          = "error"
reportUnknownMemberType             = "error"
reportUnknownVariableType           = "error"
reportUnknownArgumentType           = "error"
reportPrivateUsage                  = "error"
reportUnnecessaryCast               = "error"
reportUnknownParameterType          = "error"
reportUnnecessaryIsInstance         = "error"
reportUnusedImport                  = "error"
reportUnusedClass                   = "error"
reportUnusedFunction                = "error"
reportUnusedVariable                = "error"
reportUntypedFunctionDecorator      = "error"
reportUntypedClassDecorator         = "error"
reportUntypedBaseClass              = "error"
reportPropertyTypeMismatch          = "error"
reportIncompatibleMethodOverride    = "error"
reportIncompatibleVariableOverride  = "error"
reportOverlappingOverload           = "error"
reportUnnecessaryComparison         = "error"
reportAssertAlwaysTrue              = "error"
reportInvalidStringEscapeSequence   = "error"
reportUninitializedInstanceVariable = "error"
reportCallInDefaultInitializer      = "error"
reportUnnecessaryContains           = "error"
reportUnusedExpression              = "error"
strictListInference                 = true
strictDictionaryInference           = true
strictSetInference                  = true
analyzeUnannotatedFunctions         = true
strictParameterNoneValue            = true
enableTypeIgnoreComments            = true 
reportUnnecessaryTypeIgnoreComment  = "error"
reportImplicitOverride              = "error"
reportUnusedCallResult              = false
reportMissingTypeStubs              = "error"
reportMatchNotExhaustive            = "error"
useLibraryCodeForTypes              = true

[tool.ruff]
target-version = "py314"
line-length    = 88
extend-exclude = [
    ".local/skills",
    ".cache",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    ".venv",
    "env",
    "lib/python*",
]

[tool.ruff.lint]
select  = ["ALL"]
preview = true
ignore  = [
    "D",
    "BLE",
    "TC",
    "missing-copyright-notice",
    "no-self-use",
    "magic-value-comparison",
    "whitespace-before-punctuation",
    "multiple-spaces-before-operator",
    "multiple-spaces-after-operator",
    "multiple-spaces-after-comma",
    "unexpected-spaces-around-keyword-parameter-equals",
    "missing-whitespace-around-parameter-equals",
    "multiple-spaces-after-keyword",
    "multiple-spaces-before-keyword",
    "blank-lines-top-level",
    "line-too-long",
    "camelcase-imported-as-lowercase",
    "commented-out-code",
]

[tool.ruff.lint.mccabe]
max-complexity = 50

[tool.ruff.lint.pylint]
max-args     = 50
max-branches = 50
max-returns  = 50

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any      = false
suppress-none-returning = false

[tool.setuptools]
packages = ["core", "events", "commands"]