target-version = "py314"
line-length    = 88
preview        = true

extend-exclude = [
    ".local/skills",
    ".cache",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "env",
    "lib/python*",
]

[lint]
preview = true
select = ["ALL"]
ignore = [
    "BLE",
    "too-many-statements",
    "undocumented-public-module",
    "undocumented-public-package",
    "typing-only-first-party-import",
    "typing-only-third-party-import",
    "typing-only-standard-library-import",
    "missing-copyright-notice",
    "no-self-use",
    "magic-value-comparison",
    "whitespace-before-punctuation",
    "multiple-spaces-before-operator",
    "multiple-spaces-after-operator",
    "multiple-spaces-after-comma",
    "unexpected-spaces-around-keyword-parameter-equals",
    "multiple-spaces-after-keyword",
    "multiple-spaces-before-keyword",
    "line-too-long",
    "camelcase-imported-as-lowercase",
    "commented-out-code",
]

[lint.pydocstyle]
convention = "numpy"

[lint.mccabe]
max-complexity = 50

[lint.pylint]
max-args     = 50
max-branches = 50
max-returns  = 50

[lint.flake8-annotations]
allow-star-arg-any      = false
suppress-none-returning = false
