class BaseActions:
    def __init__(self) -> None:
        super().__init__()

    async def lockdown_add(self) -> None:
        ...

    async def lockdown_remove(self) -> None:
        ...

    async def ban_add(self) -> None:
        ...

    async def ban_view(self) -> None:
        ...

    async def ban_remove(self) -> None:
        ...

    async def kick(self) -> None:
        ...

    async def quarantine_add(self) -> None:
        ...

    async def quarantine_view(self) -> None:
        ...

    async def quarantine_remove(self) -> None:
        ...

    async def timeout_add(self) -> None:
        ...

    async def timeout_view(self) -> None:
        ...

    async def timeout_remove(self) -> None:
        ...

    async def purge(self) -> None:
        ...
